autofetch_sources: True

networks:
  default: mainnet-fork

dotenv: .env

dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.5.0
    - smartcontractkit/chainlink@1.3.1

compiler:
    solc:
        remappings:
          - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.5.0"
          - "@chainlink=smartcontractkit/chainlink@1.3.1
