name: Post vlAURA snapshot votes to voter multisig and send to the vote relayer

on:
  workflow_dispatch:
    inputs:
      manual:
        description: 'Use manual mode (true/false). Manual votes are placed in `tools/python/aura_snapshot_voting/manual_voting/{pool_type}.csv`'
        required: true
      vote-day:
        description: 'Date that votes are being posted. should be YYYY-MM-DD'
        required: true


jobs:
  generate_fees_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: vlAURA Voting
      env:
        ETHNODEURL: ${{ secrets.ETHNODEURL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
      run: |
        pwd
        cd tools/python
        pip3 install -r requirements.txt
        cd aura_snapshot_voting
        python3 vote.py ${{ github.event.inputs.manual == 'true' && ' --manual' || '' }}
    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "task: vlaura vote report"
        title: "vlaura vote report for ${{ github.event.inputs.vote-day }}"
        branch: "gha-biweekly-vlaura-votes-${{ github.event.inputs.vote-day }}"
        branch-suffix: timestamp
        delete-branch: true
        labels: "vlAURA-Vote-Report"
