name: Create Add Reewards Payload
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Reward Token'
        required: true
      gauge:
        description: 'Gauge to reward'
        required: true
      distributor:
        description: 'Distributor who can load incentives (address  or unique bal_addresses string)'
        required: false
      multisig:
        description: 'Multisig that should execute this transaction((address  or unique bal_addresses string)'
        required: true
      chain_name:
        description: 'Chain Name.  Exists in bal_addresses: One of [base, gnosis, zkevm, avalanche, mainnet, arbitrum, optimism, polygon, sepolia, mode, fraxtal]'
        required: true

jobs:
  run-script-and-create-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install git+https://github.com/BalancerMaxis/bal_addresses@0.9.5

    - name: Run script
      run: |
        cd action-scripts
        python tx_build_add_reward_token.py
      env:
        TOKEN: ${{ github.event.inputs.token }}
        GAUGE: ${{ github.event.inputs.gauge }}
        DISTRIBUTOR: ${{ github.event.inputs.distributor }}
        MULTISIG: ${{ github.event.inputs.multisig }}
        CHAIN_NAME: ${{ github.event.inputs.chain_name }}
        INFURA_KEY: ${{ secrets.INFURA_KEY }}
        ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: ERC-20 transfer payload generated by github action
        branch: erc20-xfer
        branch-suffix: timestamp
        delete-branch: true