name: Merge JSON files
env:
  LABEL: 'BIP JSON'
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]


jobs:
  merge_json:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (PR)
        if: steps.BIPJSON.outputs.hasLabel == 'true'
        uses: actions/checkout@v3
        with:
          path: pr

      - name: Check Label
        run: |
          if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
            echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '$GITHUB_SHA'"
            pull_request_labels=$(jq --raw-output '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
            if echo "$pull_request_labels" | grep -q '${{ env.LABEL }}'; then
              echo "Label '${{ env.LABEL }}' found on pull request"
            else
              echo "Label '${{ env.LABEL }} not found on pull request"
              echo "Exiting action"
              exit 1
            fi
          else
            echo "No pull request associated with commit '$GITHUB_SHA'"
            echo "Exiting action"
            exit 1
          fi

      - name: Checkout main branch for combined jsons
        uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pwd
          ls
          cd main/tools/python
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Merge JSON files
        env:
          PR_NUMBER: ${{ github.event.number }}


        run: |
          python main/tools/python/merge_pr_jsons.py

      - name: Commit and push changes
        run: |
          cd main
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Merge JSON files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
