name: Merge JSON payloads

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Directory of payloads to merge like BIPs/2023-W##'
        required: true

jobs:
  json_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Run script with JSON files
        run: |
          apt-
          python action-scripts/merge_pr_jsons.py ${{ github.event.inputs.directory }}
          npm install --save-dev --save-exact prettier
          npx prettier --write BIPs/00batched/**/*.json
      - name: pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Combined JSON Payloads ${{ github.event.inputs.directory }}"
          title: "Combined JSON payloads"
          reviewers: "solarcurvey"
          assignees: "solarcurvey"
          labels: "Gauge Payloads, Merged Payloads"
