name: Merge JSON payloads by Multisig

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Directory of payloads to merge like BIPs/2023-W##'
        required: true


jobs:
  json_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run script with JSON files
        run: |
          python action-scripts/merge_pr_json.py ${{ github.event.inputs.directory }}
      - name: pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Combined JSON Payloads"
          title: "Combined JSON payloads"
          reviewers: "solarcurvey"
          assignees: "solarcurvey"
          labels: "Automatic"
