name: Merge JSON payloads

on:
  workflow_dispatch:
    inputs:
      runWeek:
        description: 'The week to run on like YYYY-W##, should match a directory in BIPs/'
        required: true

jobs:
  json_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run script with JSON files
        run: |
          pip3 install -r action-scripts/requirements-actions.txt
          python action-scripts/merge_pr_jsons.py --target BIPs/${{ github.event.inputs.runWeek }}

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Combined JSON Payloads ${{ github.event.inputs.directory }}"
          title: "Combined JSON payloads"
          reviewers: "solarcurvey"
          assignees: "tritium-vlk"
        env:
          PR_NUMBER: ${{ steps.cpr.outputs.pull-request-number }}
          COMMIT_SHA: ${{ steps.cpr.outputs.pull-request-head-sha }}

      - name: Add Merged Payloads label
        uses: actions/github-script@v4
        with:
          script: |
            const prNumber = `${{ steps.cpr.outputs.pull-request-number }}`;
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              labels: ['Merged Payloads']
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}