name: Merge JSON payloads

on:
  workflow_dispatch:
    inputs:
      runWeek:
        description: 'The week to run on like YYYY-W##, should match a directory in BIPs/'
        required: true

jobs:
  json_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Run script with JSON files
        run: |
          pip3 install -r action-scripts/requirements-actions.txt
          python action-scripts/merge_pr_jsons.py --target ${{ github.event.inputs.runWeek }}
          npm install --save-dev --save-exact prettier
          npx prettier --write BIPs/00batched/**/*.json
          rm -rf node_modules
          rm package-lock.json
          rm package.json
      - name: pull-request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Combined JSON Payloads ${{ github.event.inputs.directory }}"
          title: "Combined JSON payloads"
          reviewers: "solarcurvey"
          assignees: "solarcurvey"
          labels: "Gauge Payloads, Merged Payloads"
