name: Merge JSON payloads

on:
  workflow_dispatch:
    inputs:
      runWeek:
        description: 'The week to run on like YYYY-W##, should match a directory in BIPs/'
        required: true

jobs:
  merge_jsons:
    runs-on: ubuntu-latest
    outputs:
      pull-request-number: ${{ steps.cpr.outputs.pull-request-number}}
      pull-request-head-sha: ${{ steps.cpr.outputs.pull-request-head-sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run script with JSON files
        run: |
          pip3 install -r action-scripts/requirements-actions.txt
          python action-scripts/merge_pr_jsons.py --target BIPs/${{ github.event.inputs.runWeek }}

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          branch-suffix: timestamp
          commit-message: "Combined JSON Payloads ${{ github.event.inputs.directory }}"
          title: "Combined JSON payloads"
          reviewers: "solarcurvey"
          assignees: "tritium-vlk"
          branch: "gha-payload-merge/autopatch"

  run_reports:
    needs: merge_jsons
    uses: "BalancerMaxis/multisig-ops/.github/workflows/run_reports_reusable.yaml@rework-reporting-and-merge-flow"
    secrets: inherit
    with:
      pr_number:  ${{ needs.merge_jsons.outputs.pull-request-number }}
      head_sha: ${{ needs.merge_jsons.outputs.pull-request-head-sha }}
