name: Merge JSON files
env:
  LABEL: 'BIP JSON'
on:
  pull_request:
    types: [ closed ]
    branches: [ main ]


jobs:
  merge_json:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: Dreamcodeio/pr-has-label-action@master
        id: 'BIP JSON'
        run: |
          echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '${{ github.sha }}'"
          COMMIT_PULL_REQUEST_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls?state=all | jq --raw-output '.[0].number')
          if [[ $COMMIT_PULL_REQUEST_NUMBER == null ]]; then
            echo "No pull request associated with commit '${{ github.sha }}'"
            exit 78
          fi
          LABEL_EXISTS=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$COMMIT_PULL_REQUEST_NUMBER/labels | jq --raw-output 'map(.name) | index("${{ env.LABEL }}")')
          if [[ $LABEL_EXISTS == null ]]; then
            echo "Label '${{ env.LABEL }}' not found on pull request $COMMIT_PULL_REQUEST_NUMBER"
            exit 78
          fi
          echo "Label '${{ env.LABEL }}' found on pull request $COMMIT_PULL_REQUEST_NUMBER"

      - name: Checkout code (PR)
        if: steps.BIPJSON.outputs.hasLabel == 'true'
        uses: actions/checkout@v3
        with:
           path: pr

      - name: Checkout main branch for combined jsons
        uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pwd
          ls
          cd main/tools/python
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Merge JSON files
        env:
          PR_NUMBER: ${{ github.event.number }}


        run: |
          python main/tools/python/merge_pr_jsons.py

      - name: Commit and push changes
        run: |
          cd main
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Merge JSON files"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
