name: Poke Onchain Rewards Injectors

on:
  workflow_dispatch:
  schedule:
  - cron: "0/5 * * * *"
env:
  KEYWORDS: ${{ secrets.KEEPER_PRIVATE_WORDS }}
jobs:
  poke_injectors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Poke'em
        run: |
          cd action-scripts/brownie
          pip3 install -r requirements-actions.txt
          touch .env
          brownie run scripts/pokeInjectors.py