name: Post vlAURA snapshot votes to voter multisig and send to the vote relayer

on:
  workflow_dispatch:
    inputs:
      week-string:
        description: 'Week string that votes are are being posted. should be YYYY-W##'
        required: true

jobs:
  post_aura_guage_votes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: vlAURA Voting
      env:
        ETHNODEURL: ${{ secrets.ETHNODEURL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        pwd
        RUN_DIR=tools/python/aura_snapshot_voting
        pip3 install -r $RUN_DIR/requirements.txt
        python3 $RUN_DIR/vote.py --week-string "${{ github.event.inputs.week-string }}"
    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "task: vlaura vote report for ${{ github.event.inputs.week-string }}"
        title: "vlaura vote report for ${{ github.event.inputs.week-string }}"
        branch: "gha-biweekly-vlaura-votes-${{ github.event.inputs.week-string }}"
        delete-branch: true
        labels: "vlAURA-Voting-Round"
