name: Process BIP PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "BIPs/**"

  workflow_run:
    workflows:
      - "Merge JSON payloads"
    types:
      - completed

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.number }}
  COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
  WEB3_INFURA_PROJECT_ID: ${{ secrets.WEB3_INFURA_PROJECT_ID }}
  ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
  ARBISCAN_TOKEN: ${{ secrets.ARBISCAN_TOKEN }}
  GNOSISSCAN_TOKEN: ${{ secrets.GNOSISSCAN_TOKEN }}
  POLYGONSCAN_TOKEN: ${{ secrets.POLYGONSCAN_TOKEN }}
  OPTIMISMSCAN_TOKEN: ${{ secrets.OPTIMISMSCAN_TOKEN }}
  ZKEVMSCAN_TOKEN: ${{ secrets.ZKEVMSCAN_TOKEN }}

jobs:
  run_reports:
    needs: merge_jsons
    uses: "BalancerMaxis/multisig-ops/.github/workflows/run_reports_reusable.yaml@rework-reporting-and-merge-flow"
    with:
      pr_number:  ${{ github.event.number }}
      head_sha: ${{ github.head_ref }}
