name: Process BIP PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "BIPs/**"
jobs:
  run_reports:
    uses: "BalancerMaxis/multisig-ops/.github/workflows/run_reports_reusable.yaml@rework-reporting-and-merge-flow"
    with:
      pr_number:  ${{ github.event.number }}
      head_sha: ${{ github.head_ref }}
