name: Review vLAURA Votes

on:
  pull_request:
    paths:
      - 'MaxiOps/vlaura_voting/**/input/*.csv'

jobs:
  review_votes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Determine week-string
        id: week-string
        run: |
          CSV_PATH=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '/input/.*\.csv$' | head -n 1)
          
          if [ -z "$CSV_PATH" ]; then
            echo "No CSV file found in recent changes."
            exit 1
          fi

          echo "CSV Path: $CSV_PATH"
          
          YEAR=$(echo $CSV_PATH | cut -d'/' -f3)
          WEEK=$(echo $CSV_PATH | cut -d'/' -f4)
          WEEK_STRING="${YEAR}-${WEEK}"

          echo "week-string=$WEEK_STRING" >> $GITHUB_OUTPUT
      - name: Review votes
        id: review
        run: |
          python tools/python/aura_snapshot_voting/review_votes.py --week-string "${{ steps.week-string.outputs.week-string }}"
      - name: Comment PR
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs');
            const reviewOutput = fs.readFileSync('review_output.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: reviewOutput
            });