name: Create Add Rewards Payload
on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Gauge (address or unique addrbook string)'
        required: true
      destination:
        description: 'Token (address)'
        required: true
      distributor:
        description: 'Distributor (address or unique addrbook string)'
        required: true
      chain_name:
        description: 'Chain Name.  Exists in bal_addresses: One of [base, gnosis, zkevm, avalanche, mainnet, arbitrum, optimism, polygon, sepolia]'
        required: true

jobs:
  create-add-rewards-payload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install web3
        pip install bal_addresses

    - name: Run script
      run: |
        cd action-scripts
        python erc20_transfer_payload.py
      env:
        TOKEN: ${{ github.event.inputs.token }}
        GAUGE: ${{ github.event.inputs.gauge }}
        DISTRIBUTOR: ${{ github.event.inputs.distibutor }}
        CHAIN_NAME: ${{ github.event.inputs.chain_name }}
        INFURA_KEY: ${{ secrets.INFURA_KEY }}
        ALCHEMY_KEY: ${{ secrets.ALCHEMY_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: ERC-20 transfer payload generated by github action
        branch: erc20-xfer
        branch-suffix: timestamp
        delete-branch: true