name: Generate new Authorizer Payloads

on:
  pull_request:
    types: [ labeled, synchronize ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LABEL: "Generate Authorizer"

jobs:
  gen_auth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/python
    steps:
    - name: Check label
      run: |
        cd $(echo '${GITHUB_WORKSPACE}')
        echo "Checking for label '${{ env.LABEL }}' on the pull request associated with commit '${{ github.sha }}'"
        COMMIT_PULL_REQUEST_NUMBER=$(curl -s https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls?state=all | jq --raw-output '.[0].number')
        if [[ $COMMIT_PULL_REQUEST_NUMBER == null ]]; then
          echo "No pull request associated with commit '${{ github.sha }}'"
          exit 78
        fi
        LABEL_EXISTS=$(curl -s https://api.github.com/repos/${{ github.repository }}/pulls/$COMMIT_PULL_REQUEST_NUMBER/labels | jq --raw-output 'map(.name) | index("${{ env.LABEL }}")')
        if [[ $LABEL_EXISTS == null ]]; then
          echo "Label '${{ env.LABEL }}' not found on pull request $COMMIT_PULL_REQUEST_NUMBER"
          exit 78
        fi
        echo "Label '${{ env.LABEL }}' found on pull request $COMMIT_PULL_REQUEST_NUMBER"

    - name: Checkout
      uses: actions/checkout@v2
      if: steps.genAuth.outputs.hasLabel == 'true'


    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Run Sweep
      run: python3 gen_add_permissions_payload.py

    - name: Commit and push changes
      uses:  stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate Fee Sweep transaction builder jsons
        commit_user_name:  GitHub Actions
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: Github Actions <noreply@users.noreply.github.com>