name: Generate new Authorizer Payloads

on:
  pull_request:
    types: [ labeled, synchronize ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  LABEL: "Generate Authorizer"

jobs:
  gen_auth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/python
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check label
      run: |
        if [ "$GITHUB_EVENT_NAME" == "pull_request" ]; then
          echo "Checking for label 'Generate Authorizer' on the pull request associated with commit '$GITHUB_SHA'"
          pull_request_labels=$(jq --raw-output '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
          if echo "$pull_request_labels" | grep -q "Generate Authorizer"; then
            echo "Label 'Generate Authorizer' found on pull request"
          else
            echo "Label 'Generate Authorizer' not found on pull request"
            echo "Exiting action"
            exit 1
          fi
        else
          echo "No pull request associated with commit '$GITHUB_SHA'"
          echo "Exiting action"
          exit 1

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Requirements
      run: pip install -r requirements.txt

    - name: Run Sweep
      run: python3 gen_add_permissions_payload.py

    - name: Commit and push changes
      uses:  stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Generate Fee Sweep transaction builder jsons
        commit_user_name:  GitHub Actions
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: Github Actions <noreply@users.noreply.github.com>