name: Validate BIPs

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    paths:
      - "BIPs/**"

env:
  LABEL: 'BIPs validation'

jobs:
  payload_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Generate report
      id: gen-report
      env:
        PR_NUMBER: ${{ github.event.number }}
        COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        cd action-scripts/brownie
        touch .env
        pip install -r requirements-actions.txt
        brownie run --network mainnet scripts/validate_bip.py
        REPORT=`cat validate_bip_results.txt`
        echo output.txt "::set-output name=report-data::$REPORT"

    - name: Post Validation Report as Comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: action-scripts/brownie/validate_bip_results.txt
        reactions: eyes

    - name: Commit and push validation reports
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Adding gauge reports to json payloads
        commit_user_name: GitHub Actions
        commit_user_email: github-actions[bot]@users.noreply.github.com
        commit_author: Github Actions <noreply@users.noreply.github.com>