name: Post vlAURA snapshot votes to voter multisig and send to the vote relayer

on:
  workflow_dispatch:
    inputs:
      week-string:
        description: 'Week string that votes are being posted. should be YYYY-W##'
        required: true

jobs:
  generate_fees_report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip3 install -r tools/python/requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Verify input directory
      run: |
        week_string="${{ github.event.inputs.week-string }}"
        year=$(echo $week_string | cut -d'-' -f1)
        week=$(echo $week_string | cut -d'-' -f2)
        input_dir="${{ github.workspace }}/MaxiOps/vlaura_voting/${year}/${week}/input"
        echo "Expected input directory: $input_dir"
        if [ -d "$input_dir" ]; then
          echo "Input directory exists."
          ls -la "$input_dir"
        else
          echo "Input directory does not exist."
        fi

    - name: vlAURA Voting
      env:
        ETHNODEURL: ${{ secrets.ETHNODEURL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        pwd
        ls -la tools/python/aura_snapshot_voting
        python3 tools/python/aura_snapshot_voting/vote.py --week-string "${{ github.event.inputs.week-string }}"
      working-directory: ${{ github.workspace }}

    - name: Create PR
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: "task: vlaura vote report"
        title: "vlaura vote report for ${{ github.event.inputs.week-string }}"
        branch: "gha-biweekly-vlaura-votes-${{ github.event.inputs.week-string }}"
        branch-suffix: timestamp
        delete-branch: true
        labels: "vlAURA-Vote-Report"